[project]
name = "desafio-autorizador"
version = "1.0.0"
description = "Nubank - Desafio Autorizador"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
desafio-autorizador = "desafio_autorizador.main:main"

[project.optional-dependencies]
dev = ["ruff", "black", "isort", "commitizen", "pre-commit"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ["py38"]
exclude = '''
/(
    \.venv
  | dist
  | build
)/
'''

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["desafio_autorizador"]
skip = [".venv", "dist", "build"]

[tool.ruff]
line-length = 88
target-version = "py38"
exclude = [".venv", "dist", "build"]

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = ["E501"]  # Ignora linhas longas, pois o Black jรก cuida disso

[tool.commitizen]
name = "cz_conventional"
version = "1.0.0"
tag_format = "v$version"
version_files = [
    "pyproject.toml:version",
]
update_changelog_on_bump = true
changelog_incremental = true
